### ISSUE TITLE
Load multi service error.

### ISSUE THREAD

**Issue by Quesle** [flyingSprite/adminPlan#8]
Always get error message:

```
require.min.js [sm]:900 TypeError: t.directive(...).service(...).service is not a function
    at http://localhost:9000/dist/ap.service.all.min.js:1:3601
    at Object.execCb (http://localhost:9000/dist/require.min.js:1:12778)
    at Object.check (http://localhost:9000/dist/require.min.js:1:6468)
    at Object.<anonymous> (http://localhost:9000/dist/require.min.js:1:9046)
    at http://localhost:9000/dist/require.min.js:1:761
    at http://localhost:9000/dist/require.min.js:1:9507
    at each (http://localhost:9000/dist/require.min.js:1:236)
    at Object.emit (http://localhost:9000/dist/require.min.js:1:9475)
    at Object.check (http://localhost:9000/dist/require.min.js:1:7187)
    at Object.enable (http://localhost:9000/dist/require.min.js:1:9373)
```

**Comment by Quesle** [comment]
Because define directive and service by 

``` javascript
app.directive('myDir', function() {
  // do ...
})
.service('mySer', , function() {
  // do ...
});
```

This is not good.

Write by:

``` javascript
app.directive('myDir', function() {
  // do ...
});
app.service('mySer', , function() {
  // do ...
});
```
